package ws.agricultor.model;
// Generated 11/04/2023 09:09:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgrEstados generated by hbm2java
 */
@Entity
@Table(name="agr_estados"
    ,catalog="db_agricultor"
)
public class AgrEstados  implements java.io.Serializable {


     private Integer idEstado;
     private String nombreEstado;
     private String descripcion;
     private Character estado;
     private String usuarioCreacion;
     private Date fechaCreacion;
     private Set<AgrCuentaCorriente> agrCuentaCorrientes = new HashSet(0);
     private Set<AgrTransportistas> agrTransportistases = new HashSet(0);
     private Set<AgrVehiculos> agrVehiculoses = new HashSet(0);
     private Set<AgrParcialidades> agrParcialidadeses = new HashSet(0);
     private Set<AgrMensajes> agrMensajeses = new HashSet(0);

    public AgrEstados() {
    }

	
    public AgrEstados(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public AgrEstados(String nombreEstado, String descripcion, Character estado, String usuarioCreacion, Date fechaCreacion, Set<AgrCuentaCorriente> agrCuentaCorrientes, Set<AgrTransportistas> agrTransportistases, Set<AgrVehiculos> agrVehiculoses, Set<AgrParcialidades> agrParcialidadeses, Set<AgrMensajes> agrMensajeses) {
       this.nombreEstado = nombreEstado;
       this.descripcion = descripcion;
       this.estado = estado;
       this.usuarioCreacion = usuarioCreacion;
       this.fechaCreacion = fechaCreacion;
       this.agrCuentaCorrientes = agrCuentaCorrientes;
       this.agrTransportistases = agrTransportistases;
       this.agrVehiculoses = agrVehiculoses;
       this.agrParcialidadeses = agrParcialidadeses;
       this.agrMensajeses = agrMensajeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_ESTADO", unique=true, nullable=false)
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="NOMBRE_ESTADO", length=50)
    public String getNombreEstado() {
        return this.nombreEstado;
    }
    
    public void setNombreEstado(String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }

    
    @Column(name="DESCRIPCION", length=40)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="ESTADO", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }

    
    @Column(name="USUARIO_CREACION", length=50)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA_CREACION", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "agrEstados")
    public Set<AgrCuentaCorriente> getAgrCuentaCorrientes() {
        return agrCuentaCorrientes;
    }

    public void setAgrCuentaCorrientes(Set<AgrCuentaCorriente> agrCuentaCorrientes) {
        this.agrCuentaCorrientes = agrCuentaCorrientes;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "agrEstados")
    public Set<AgrTransportistas> getAgrTransportistases() {
        return agrTransportistases;
    }

    public void setAgrTransportistases(Set<AgrTransportistas> agrTransportistases) {
        this.agrTransportistases = agrTransportistases;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "agrEstados")
    public Set<AgrVehiculos> getAgrVehiculoses() {
        return agrVehiculoses;
    }

    public void setAgrVehiculoses(Set<AgrVehiculos> agrVehiculoses) {
        this.agrVehiculoses = agrVehiculoses;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "agrEstados")
    public Set<AgrParcialidades> getAgrParcialidadeses() {
        return agrParcialidadeses;
    }

    public void setAgrParcialidadeses(Set<AgrParcialidades> agrParcialidadeses) {
        this.agrParcialidadeses = agrParcialidadeses;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "agrEstados")
    public Set<AgrMensajes> getAgrMensajeses() {
        return agrMensajeses;
    }

    public void setAgrMensajeses(Set<AgrMensajes> agrMensajeses) {
        this.agrMensajeses = agrMensajeses;
    }


}


