package ws.cafetito.model;
// Generated 11/04/2023 09:09:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BcEstados generated by hbm2java
 */
@Entity
@Table(name="bc_estados" , schema="db_cafetito")
public class BcEstados  implements java.io.Serializable {


     private Integer idEstado;
     private String nombreEstado;
     private String descripcion;
     private Character estado;
     private String usuarioCreacion;
     private Date fechaCreacion;
     private Set<BcCuentaCorriente> bcCuentaCorriente = new HashSet(0);
     private Set<BcTransportistas> bcTransportistas = new HashSet(0);
     private Set<BcVehiculos> bcVehiculos = new HashSet(0);
     private Set<BcParcialidades> bcParcialidades = new HashSet(0);
     private Set<BcMensajes> bcMensajes = new HashSet(0);

    public BcEstados() {
    }

	
    public BcEstados(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public BcEstados(String nombreEstado, String descripcion, Character estado, String usuarioCreacion, Date fechaCreacion, Set<BcCuentaCorriente> bcCuentaCorriente, Set<BcTransportistas> bcTransportistas, Set<BcVehiculos> bcVehiculos, Set<BcParcialidades> bcParcialidades, Set<BcMensajes> bcMensajes) {
       this.nombreEstado = nombreEstado;
       this.descripcion = descripcion;
       this.estado = estado;
       this.usuarioCreacion = usuarioCreacion;
       this.fechaCreacion = fechaCreacion;
       this.bcCuentaCorriente = bcCuentaCorriente;
       this.bcTransportistas = bcTransportistas;
       this.bcVehiculos = bcVehiculos;
       this.bcParcialidades = bcParcialidades;
       this.bcMensajes = bcMensajes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_ESTADO", unique=true, nullable=false)
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="NOMBRE_ESTADO", length=50)
    public String getNombreEstado() {
        return this.nombreEstado;
    }
    
    public void setNombreEstado(String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }

    
    @Column(name="DESCRIPCION", length=40)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="ESTADO", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }

    
    @Column(name="USUARIO_CREACION", length=50)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA_CREACION", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="bcEstados")
    public Set<BcCuentaCorriente> getBcCuentaCorriente() {
        return this.bcCuentaCorriente;
    }
    
    public void setBcCuentaCorriente(Set<BcCuentaCorriente> bcCuentaCorriente) {
        this.bcCuentaCorriente = bcCuentaCorriente;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="bcEstados")
    public Set<BcTransportistas> getBcTransportistas() {
        return this.bcTransportistas;
    }
    
    public void setBcTransportistas(Set<BcTransportistas> bcTransportistas) {
        this.bcTransportistas = bcTransportistas;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="bcEstados")
    public Set<BcVehiculos> getBcVehiculos() {
        return this.bcVehiculos;
    }
    
    public void setBcVehiculos(Set<BcVehiculos> bcVehiculos) {
        this.bcVehiculos = bcVehiculos;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="bcEstados")
    public Set<BcParcialidades> getBcParcialidades() {
        return this.bcParcialidades;
    }
    
    public void setBcParcialidades(Set<BcParcialidades> bcParcialidades) {
        this.bcParcialidades = bcParcialidades;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="bcEstados")
    public Set<BcMensajes> getBcMensajes() {
        return this.bcMensajes;
    }
    
    public void setBcMensajes(Set<BcMensajes> BcMensajes) {
        this.bcMensajes = BcMensajes;
    }




}


