package ws.cafetito.model;
// Generated 11/04/2023 09:09:22 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BcParcialidades generated by hbm2java
 */
@Entity
@Table(name="bc_parcialidades" , schema="db_cafetito")
public class BcParcialidades  implements java.io.Serializable {


     private Integer idParcialidad;
     private BcCuentaCorriente bcCuentaCorriente;
     private BcEstados bcEstados;
     private BigDecimal pesoParcialidad;
     private Date fechaParcialidadEnviada;
     private Date fechaParcialidadEntregada;
     private String licenciasTransportistas;
     private String placaVehiculo;
     private String usuarioCreacion;
     private Date fechaCreacion;
     private Set<BcBoletaPesaje> bcBoletaPesajes = new HashSet(0);

    public BcParcialidades() {
    }

	
    public BcParcialidades(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public BcParcialidades(BcCuentaCorriente bcCuentaCorriente, BcEstados bcEstados, BigDecimal pesoParcialidad, Date fechaParcialidadEnviada, Date fechaParcialidadEntregada, String licenciasTransportistas, String placaVehiculo, String usuarioCreacion, Date fechaCreacion, Set<BcBoletaPesaje> bcBoletaPesajes) {
       this.bcCuentaCorriente = bcCuentaCorriente;
       this.bcEstados = bcEstados;
       this.pesoParcialidad = pesoParcialidad;
       this.fechaParcialidadEnviada = fechaParcialidadEnviada;
       this.fechaParcialidadEntregada = fechaParcialidadEntregada;
       this.licenciasTransportistas = licenciasTransportistas;
       this.placaVehiculo = placaVehiculo;
       this.usuarioCreacion = usuarioCreacion;
       this.fechaCreacion = fechaCreacion;
       this.bcBoletaPesajes = bcBoletaPesajes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_PARCIALIDAD", unique=true, nullable=false)
    public Integer getIdParcialidad() {
        return this.idParcialidad;
    }
    
    public void setIdParcialidad(Integer idParcialidad) {
        this.idParcialidad = idParcialidad;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="NUMERO_CUENTA")
    public BcCuentaCorriente getBcCuentaCorriente() {
        return this.bcCuentaCorriente;
    }
    
    public void setBcCuentaCorriente(BcCuentaCorriente bcCuentaCorriente) {
        this.bcCuentaCorriente = bcCuentaCorriente;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ESTADO_PARCIALIDAD")
    public BcEstados getBcEstados() {
        return this.bcEstados;
    }
    
    public void setBcEstados(BcEstados bcEstados) {
        this.bcEstados = bcEstados;
    }

    
    @Column(name="PESO_PARCIALIDAD", precision=10)
    public BigDecimal getPesoParcialidad() {
        return this.pesoParcialidad;
    }
    
    public void setPesoParcialidad(BigDecimal pesoParcialidad) {
        this.pesoParcialidad = pesoParcialidad;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA_PARCIALIDAD_ENVIADA", length=19)
    public Date getFechaParcialidadEnviada() {
        return this.fechaParcialidadEnviada;
    }
    
    public void setFechaParcialidadEnviada(Date fechaParcialidadEnviada) {
        this.fechaParcialidadEnviada = fechaParcialidadEnviada;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA_PARCIALIDAD_ENTREGADA", length=19)
    public Date getFechaParcialidadEntregada() {
        return this.fechaParcialidadEntregada;
    }
    
    public void setFechaParcialidadEntregada(Date fechaParcialidadEntregada) {
        this.fechaParcialidadEntregada = fechaParcialidadEntregada;
    }

    
    @Column(name="LICENCIAS_TRANSPORTISTAS", length=100)
    public String getLicenciasTransportistas() {
        return this.licenciasTransportistas;
    }
    
    public void setLicenciasTransportistas(String licenciasTransportistas) {
        this.licenciasTransportistas = licenciasTransportistas;
    }

    
    @Column(name="PLACA_VEHICULO", length=10)
    public String getPlacaVehiculo() {
        return this.placaVehiculo;
    }
    
    public void setPlacaVehiculo(String placaVehiculo) {
        this.placaVehiculo = placaVehiculo;
    }

    
    @Column(name="USUARIO_CREACION", length=50)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA_CREACION", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="bcParcialidades") 
    public Set<BcBoletaPesaje> getBcBoletaPesajes() {
        return this.bcBoletaPesajes;
    }
    
    public void setBcBoletaPesajes(Set<BcBoletaPesaje> bcBoletaPesajes) {
        this.bcBoletaPesajes = bcBoletaPesajes;
    }




}


